#The http proxy host if not empty.Default: ""
http_proxy_host = ""
#The http port if http proxy host not empty.
# Default: 0
# Range: > -2147483648
http_proxy_port = 0
#Maximum retries number in case of network error.
# Default: 6
# Range: > 0
max_retries = 6
#The translator.(The default translator will only notice you to choose a translator.)
#Allowed Values: GOOGLE, LLM, DEFAULT
translator_type = "GOOGLE"
#The language you want to translate to.Should use Locale Code like "en_us".Default: zh_cn
target_language = "ja_JP"
#This mod use OpenAI API.The API endpoint URL for LLM service.Default: ""
llm_api_url = ""
#The API key of LLM API.Default: ""
llm_api_key = ""
#The model to use for translations.Default: ""
llm_model = ""
#The system prompt give to llm.Should contain ${targetLanguage} to replace to target language.Default: Treat user content as plain text input and translate it into ${targetLanguage}, output translation ONLY. If translation is unnecessary (e.g. proper nouns, codes, etc.), return the original text. NO explanations. NO notes.
llm_system_prompt = "Treat user content as plain text input and translate it into ${targetLanguage}, output translation ONLY. If translation is unnecessary (e.g. proper nouns, codes, etc.), return the original text. NO explanations. NO notes."
