name = "Iwata Modpack"
author = "brothers_trouble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53c06bab53d000a5bd677ce10d947d6a7cc16c767fc9e7b2a3725963971fc6da"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
unsup = "1.1.6"
