name = "Iwata Modpack"
author = "brothers_trouble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a10acde9043e7d9449a6ed280e71ee272d7242a3210ca104435d9419b2cc8d3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
unsup = "1.1.6"
