name = "Iwata Modpack"
author = "brothers_trouble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de894705ab37aea0b750b33cc460b1d0ebc73b6ee4a502b8ea3ade3b2edf3c0a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
unsup = "1.1.6"
